#server.port=8083
#spring.application.name=api-gateway

# Configuración de las rutas del Gateway hacia tu puerto 3031
#spring.cloud.gateway.routes[0].id=usuarios-portfolios-service
#spring.cloud.gateway.routes[0].uri=http://localhost:8081
#spring.cloud.gateway.routes[0].predicates[0]=Path=/usuarios/**, /portfolios/**
#spring.cloud.gateway.routes[0].filters[0]=TokenRelay

# Configuración de los endpoints de Keycloak
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/users-tp
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/users-tp/protocol/openid-connect/certs


server.port=8083
spring.application.name=api-gateway

# Yahoo finance
spring.cloud.gateway.routes[0].id=servicio-yahoo-api-finance
spring.cloud.gateway.routes[0].uri=http://localhost:8084
spring.cloud.gateway.routes[0].predicates[0]=Path=/servidormock/api/v1/**

# Usuarios Portfolios
spring.cloud.gateway.routes[1].id=usuarios-portfolios-service
# Como ambos corren dentro de Docker, usamos el nombre del contenedor
spring.cloud.gateway.routes[1].uri=http://usuarios-portfolios:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/usuarios/**
spring.cloud.gateway.routes[1].filters[0]=TokenRelay

# Enlaces de validaci�n de seguridad hacia tu Keycloak en Docker
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/users-tp
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/users-tp/protocol/openid-connect/certs
