# --- RUTAS PARA DOCKER ---
spring.cloud.gateway.routes[0].id=servicio-yahoo-api-finance
spring.cloud.gateway.routes[0].uri=http://servicio-yahoo-api-finance:8084
spring.cloud.gateway.routes[0].predicates[0]=Path=/servidormock/api/v1/**

spring.cloud.gateway.routes[1].id=usuarios-registro
spring.cloud.gateway.routes[1].uri=http://tp-usuarios-portfolios:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/usuarios/registro,/api/ventas/**

spring.cloud.gateway.routes[2].id=usuarios-portfolios-service
spring.cloud.gateway.routes[2].uri=http://tp-usuarios-portfolios:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/usuarios/**,/api/portfolios/**,/api/billetera/**,/api/ventas/**
spring.cloud.gateway.routes[2].filters[0]=TokenRelay

# --- KEYCLOAK DOCKER ---
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8180/realms/users-tp
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8180/realms/users-tp/protocol/openid-connect/certs
