server.port=8083
spring.application.name=api-gateway

# Configuración de las rutas del Gateway hacia tu puerto 3031
spring.cloud.gateway.routes[0].id=usuarios-registro
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/registro

spring.cloud.gateway.routes[1].id=usuarios-portfolios-service
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/usuarios/**, /api/billetera/**
spring.cloud.gateway.routes[1].filters[0]=TokenRelay



# Configuración de los endpoints de Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/users-tp
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/users-tp/protocol/openid-connect/certs