spring.application.name=servicio-yahoo-api-finance

server.port=8084

server.servlet.context-path=/servidormock/api/v1


# Para ver las metricas de Prometheus
# http://localhost:8083/servidormock/api/v1/actuator/prometheus
management.endpoints.web.exposure.include=prometheus

