server.port=8083
spring.application.name=api-gateway

# --- RUTA 0: API de Yahoo Finance Mock ---
spring.cloud.gateway.routes[0].id=servicio-yahoo-api-finance
spring.cloud.gateway.routes[0].uri=http://localhost:8084
spring.cloud.gateway.routes[0].predicates[0]=Path=/servidormock/api/v1/**

# --- RUTA 1: Registro (Pública - SIN TokenRelay) ---
spring.cloud.gateway.routes[1].id=usuarios-registro
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/usuarios/registro,/api/ventas/**

# --- RUTA 2: Todo lo demás (Privada - CON TokenRelay) ---
spring.cloud.gateway.routes[2].id=usuarios-portfolios-service
spring.cloud.gateway.routes[2].uri=http://localhost:8081
# ¡Ojo acá! Sin un solo espacio después de las comas
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/usuarios/**,/api/portfolios/**,/api/billetera/**
spring.cloud.gateway.routes[2].filters[0]=TokenRelay

# --- ENLACES HACIA TU CONTENEDOR EN EL PUERTO 8180 ---
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/users-tp
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/users-tp/protocol/openid-connect/certs
