version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: tp-keycloak-auth
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

      # --- PERSISTENCIA: Conectamos Keycloak a MySQL ---
      - KC_DB=mysql
      # Apuntamos al servicio 'mysql-db' y a su base de datos asignada
      - KC_DB_URL=jdbc:mysql://mysql-db:3306/keycloak_db?createDatabaseIfNotExist=true
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
    ports:
      - "8080:8080"
    volumes:
      # Limpiamos el espacio vacío y mantenemos el mapeo a tu volumen en disco
      - keycloak_data:/opt/keycloak/data
    networks:
      - tp-network
    restart: unless-stopped
    depends_on:
      - mysql-db # Forzamos a Keycloak a esperar que MySQL esté listo

  mysql-db:
    image: mysql:8.0
    container_name: contenedor-mysql2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios_db
    volumes:
      - mysql_data:/var/lib/mysql
      # TRUCO DE AUTOMATIZACIÓN: Script en memoria para forzar la creación de la BD de Keycloak
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - tp-network
    restart: unless-stopped

  # --- Tu backend de Java 17 ---
  usuarios-portfolios-service:
    build:
      context: ../../usuarios-portfolios
      dockerfile: Dockerfile
    container_name: tp-usuarios-portfolios
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_DATABASE=usuarios_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      - mysql-db
    networks:
      - tp-network
    restart: unless-stopped

volumes:
  keycloak_data:
    driver: local
  mysql_data:
    driver: local

networks:
  tp-network:
    driver: bridge